name: Ezra Bible App test suite

on: push

jobs:
    #unit-test:
    #    name: Run jest tests
    #    runs-on: ubuntu-24.04
    #    timeout-minutes: 10
    #    steps:
    #    - uses: actions/checkout@v2
    #    - uses: actions/setup-node@v2
    #      with:
    #        node-version: '14'
    #
    #    - name: Install package.json dependencies (except node-sword-interface)
    #      run: npm uninstall node-sword-interface
    #    
    #    - name: Run test
    #      run: npm run test

    e2e-test:
        name: Run Cucumber tests
        runs-on: ubuntu-22.04
        timeout-minutes: 12
        env:
          JOBS: MAX

        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: '14'

        - name: Install apt dependencies
          run: sudo apt update && sudo apt install -y libcurl4-gnutls-dev xvfb subversion
        
        - name: Install node dependencies and build native modules
          run: npm install
        
        - name: Install electron v17.1.0 for compatibility with Spectron
          run: npm install electron@17.1.0

        - name: Compile templates
          run: npm run compile-pug 

        - name: Run test
          uses: nick-fields/retry@v2
          with:
            timeout_minutes: 5
            max_attempts: 3
            command: npm run headless-test

        - name: Archive screenshot (in case of an error)
          uses: actions/upload-artifact@v4.4.0
          if: failure()
          with:
            name: screenshot.png
            path: ./test_screenshot.png
