name: Ezra Project test suite

on: push

jobs:
    test:
        name: Run Cucumber tests
        runs-on: ubuntu-20.04
        steps:
        - name: Checkout
          uses: actions/checkout@v1

        - name: Install dependencies
          uses: docker://toklein/ezra-ubuntu-2004:latest
          with:
            entrypoint: /usr/bin/npm
            args: install
        
        - name: Compile templates
          run: npm run compile-pug
        
        - name: Bundle JS
          run: npm run bundle

        - name: Minify JS
          run: npm run minify

        - name: Run test
          run: npm run full-test
          env:
            JOBS: MAX

        - name: Archive screenshot (in case of an error)
          uses: actions/upload-artifact@v2
          if: failure()
          with:
            name: screenshot.png
            path: ./test_screenshot.png